DROP DATABASE IF EXISTS YouthGroup;
CREATE DATABASE YouthGroup;
USE YouthGroup;

-- GUARDIAN
CREATE TABLE Guardian (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50)
);

-- STUDENT
CREATE TABLE Student (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    GuardianID INT,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    FOREIGN KEY (GuardianID) REFERENCES Guardian(ID)
);

-- GROUP
CREATE TABLE `Group` (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100)
);

-- GROUP LEADER
CREATE TABLE GroupLeader (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    GroupID INT,
    FOREIGN KEY (GroupID) REFERENCES `Group`(ID)
);

-- LEADER
CREATE TABLE Leader (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50)
);

-- EVENT
CREATE TABLE Event (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Type VARCHAR(100),
    Notes TEXT
);

-- EVENT LEADER
CREATE TABLE EventLeader (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    LeaderID INT,
    EventID INT,
    FOREIGN KEY (LeaderID) REFERENCES Leader(ID),
    FOREIGN KEY (EventID) REFERENCES Event(ID)
);

-- GROUP MEMBER
CREATE TABLE GroupMember (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    GroupID INT,
    StudentID INT,
    Name VARCHAR(100),
    FOREIGN KEY (GroupID) REFERENCES `Group`(ID),
    FOREIGN KEY (StudentID) REFERENCES Student(ID)
);

-- VOLUNTEER
CREATE TABLE Volunteer (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50)
);

-- VOLUNTEER RECORD
CREATE TABLE VolunteerRecord (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    VolunteerID INT,
    EventID INT,
    FOREIGN KEY (VolunteerID) REFERENCES Volunteer(ID),
    FOREIGN KEY (EventID) REFERENCES Event(ID)
);

-- ATTENDANCE RECORD
CREATE TABLE AttendanceRecord (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EventID INT,
    Date DATE,
    Time TIME,
    RSVP BOOLEAN,
    FOREIGN KEY (EventID) REFERENCES Event(ID)
);